{{- $imageAutonity := .Values.imageAutonity -}}
{{- $imageAutonity_init := .Values.imageAutonity_init -}}
{{- $imagePrometheusExporter := .Values.image_prometheus_exporter -}}
{{- $imageNginx := .Values.image_nginx -}}
{{- $namespace := .Release.Namespace -}}
{{- $releasename := .Release.Name -}}

{{- $ethstatsEnabled :=  .Values.global.ethstats.enabled -}}
{{- $prometheusEnabled :=  .Values.global.prometheus.enabled -}}
{{- $rpcHttpBasicAuthEnabled :=  .Values.rpc_http_basic_auth_enabled -}}
{{- $rpcHttpsEnabled :=  .Values.rpc_https_enabled -}}
{{- $awsPersistentStorageEnabled :=  .Values.aws_persistent_storage_enabled -}}
{{- $gcpPersistentStorageEnabled :=  .Values.gcp_persistent_storage_enabled -}}

{{ range $i, $e := until (atoi (printf "%d" (int64 .Values.validators))) }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: validator-{{ $i }}
  namespace: {{ $namespace }}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: validator-{{ $i }}
    spec:
      initContainers:
      - name: init
        image: {{ $imageAutonity_init.repository }}:{{ $imageAutonity_init.tag }}
        volumeMounts:
        - name: blockchain
          mountPath: /autonity/blockchain
        - name: keys
          mountPath: /autonity/keys
        - name: cm-genesis
          mountPath: /autonity/cm-genesis
        - name: sec-account-pwd
          mountPath: /autonity/sec-account-pwd
        - name: sec-peers
          mountPath: /autonity/sec-peers
      containers:
      - name: autonity
        image: {{ $imageAutonity.repository }}:{{ $imageAutonity.tag }}
        ports:
        - containerPort: 30303
          name: p2p
        args:
          - "--datadir"
          - "/autonity/blockchain"
          - "--keystore"
          - "/autonity/keys/keystore"
          - "--nodekey"
          - "/autonity/sec-peers/private_key"
          - "--gcmode"
          - "archive"
          - "--syncmode"
          - "full"
          - "--cache"
          - "1024"
          - "--rpc"
          - "--rpcapi"
          - "eth,web3,net,txpool,debug"
          - "--rpcvhosts"
          - "*"
          - "--ws"
          - "--wsapi"
          - "eth,web3,net"
          - "--wsorigins"
          - "*"
          - "--metrics"
          - "--mine"
          - "--minerthreads"
          - "1"
          - "--debug"
          - "--verbosity"
          - "4"
{{ if $ethstatsEnabled }}
          - "--ethstats"
          - "validator-{{ $i }}:$(ETHSTATS_SECRET)@ethstats.{{ $namespace }}"
        env:
        - name: ETHSTATS_SECRET
          valueFrom:
            secretKeyRef:
              name: ethstats
              key: WS_SECRET
{{ end }}
        volumeMounts:
        - name: blockchain
          mountPath: /autonity/blockchain
        - name: keys
          mountPath: /autonity/keys
        - name: sec-peers
          mountPath: /autonity/sec-peers
{{ if $prometheusEnabled }}
      - name: prometheus-exporter
        image: {{ $imagePrometheusExporter.repository }}:{{ $imagePrometheusExporter.tag }}
        ports:
        - containerPort: 9200
          name: metrics
        command: ['geth_exporter', '-ipc', '/autonity/blockchain/autonity.ipc']
        volumeMounts:
        - name: blockchain
          mountPath: /autonity/blockchain
{{ end }}
      - name: nginx
        image: {{ $imageNginx.repository }}:{{ $imageNginx.tag }}
        ports:
        - containerPort: 8080
          name: https-rpc
        volumeMounts:
        - name: nginx-proxy-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
{{ if $rpcHttpBasicAuthEnabled }}
        - name: nginx-proxy-config
          mountPath: /etc/nginx/htpasswd
          subPath: htpasswd
{{ end }}
{{ if $rpcHttpsEnabled }}
        - name: nginx-proxy-ssl
          mountPath: /etc/nginx/ssl
{{ end }}
      volumes:
        - name: blockchain
{{ if or (eq $awsPersistentStorageEnabled true) (eq $gcpPersistentStorageEnabled true)}}
          persistentVolumeClaim:
            claimName: {{ $releasename }}-validator-{{ $i }}-blockchain
{{ else }}
          emptyDir: {}
{{ end}}
        - name: keys
          emptyDir:
            medium: Memory
            sizeLimit: "1M"
        - name: cm-genesis
          configMap:
            name: genesis
        - name: sec-account-pwd
          secret:
            secretName: account-pwd
        - name: sec-peers
          secret:
            secretName: validators
            items:
              - key: {{ $i }}.private_key
                path: private_key
        - name: nginx-proxy-config
          configMap:
            name: nginx-conf
{{ if $rpcHttpsEnabled }}
        - name: nginx-proxy-ssl
          secret:
            secretName: autonity-https
{{ end }}
{{- end}}
