{{- if .Values.rpc_https_enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: autonity-https
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: |-
    {{ .Files.Get (printf "%s/%s" .Values.files_dir "tls.crt" ) | b64enc }}
  tls.key: |-
    {{ .Files.Get (printf "%s/%s" .Values.files_dir "tls.key" ) | b64enc }}
  dhparam.pem: |-
    {{ .Files.Get (printf "%s/%s" .Values.files_dir "dhparam.pem" ) | b64enc }}
---
{{- end }}
