{{- $namespace := .Release.Namespace -}}

{{- $serviceType :=  .Values.validators.serviceType -}}
{{- $ips :=  .Values.validators.ips -}}

{{ range $i, $e := until (atoi (printf "%d" (int64 .Values.validators.num))) }}
---
apiVersion: v1
kind: Service
metadata:
  name: validator-{{ $i }}
  namespace: {{ $namespace }}
  annotations:
    prometheus.io/port: "6060"
    prometheus.io/path: "/debug/metrics/prometheus"
    prometheus.io/scrape: "true"
spec:
  type: {{ $serviceType }}
  {{ if eq $serviceType "LoadBalancer" }}
  loadBalancerIP: {{index $ips $i }}
  {{ end }}
  ports:
    - protocol: TCP
      name: https-rpc
      port: 8545
      targetPort: 8080
    - protocol: TCP
      name: wss
      port: 8546
      targetPort: 8081
    - protocol: TCP
      name: p2p
      port: 30303
      targetPort:  30303
    - protocol: TCP
      name: metrics
      port: 6060
      targetPort: 6060
  selector:
    app: validator-{{ $i }}
{{- end}}
