{{- $namespace := .Release.Namespace -}}
{{- $prometheusEnabled :=  .Values.global.prometheus.enabled -}}

{{ range $i, $e := until (atoi (printf "%d" (int64 .Values.observers))) }}
---
apiVersion: v1
kind: Service
metadata:
  name: observer-{{ $i }}
  namespace: {{ $namespace }}
{{ if $prometheusEnabled }}
  annotations:
    prometheus.io/port: "9200"
    prometheus.io/scrape: "true"
{{ end }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: https-rpc
      port: 8545
      targetPort: 8080
    - protocol: TCP
      name: p2p
      port: 30303
      targetPort:  30303
{{ if $prometheusEnabled }}
    - protocol: TCP
      name: metrics
      port: 9200
      targetPort: 9200
{{ end }}
  selector:
    app: observer-{{ $i }}
{{- end}}
