{{- $namespace := .Release.Namespace -}}

{{ range $i, $e := until (atoi (printf "%d" (int64 .Values.observers))) }}
---
apiVersion: v1
kind: Service
metadata:
  name: observer-{{ $i }}
  namespace: {{ $namespace }}
  annotations:
    prometheus.io/port: "6060"
    prometheus.io/path: "/debug/metrics/prometheus"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: https-rpc
      port: 8545
      targetPort: 8080
    - protocol: TCP
      name: wss
      port: 8546
      targetPort: 8081
    - protocol: TCP
      name: p2p
      port: 30303
      targetPort:  30303
    - protocol: TCP
      name: metrics
      port: 6060
      targetPort: 6060
  selector:
    app: observer-{{ $i }}
{{- end}}
