dist: bionic
sudo: required
cache:
  directories:
  - "$HOME/bin"
before_install:
- mkdir -p ~/bin
- if [ ! -f ~/bin/kubectl ]; then curl -Ls -o ~/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl
  -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl;
  fi
- chmod +x ~/bin/*
- export PATH="~/bin:$PATH"
- sudo snap install google-cloud-sdk
- echo $BASE64_GOOGLE_CLOUD_KEYFILE_JSON | base64 -d > gcp_cred.json
- gcloud auth activate-service-account --key-file gcp_cred.json
- curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
- chmod 700 get_helm.sh
- sudo ./get_helm.sh --version ${HELM_VERSION}
jobs:
  include:
  - if: type = pull_request AND fork = true AND branch = candidate
    script:
    - "./ci/test_candidate_pr.sh"
  - if: type = pull_request AND fork = false AND head_repo = clearmatics/charts-ose
      AND commit_message !~ /WIP/
    env:
    - GCP_CLUSTER=tf-gke-helm
    - CHART_NAME=${TRAVIS_PULL_REQUEST_BRANCH}
    script:
    - "./ci/test_chart.sh $GCP_CLUSTER $CHART_NAME"
  - if: fork = false AND (sender = eastata OR sender = Klazomenai OR sender = scarby OR sender = raj-shekhar1) AND tag =~ /^(\w|-)*[-]\d+[.]\d+[.]\d+$/
    env:
    - GCP_CLUSTER=tf-gke-helm
    - S3_BUCKET_NAME=charts-ose.clearmatics.com
    - CHART_NAME=$(echo ${TRAVIS_TAG} | sed -E s/-[0-9]+\.[0-9]+\.[0-9]+$//g)
    - RELEASE_VERSION=$(echo ${TRAVIS_TAG} | grep -Eo [0-9]+\.[0-9]+\.[0-9]+$)
    script:
    - aws eks update-kubeconfig --name ${GCP_CLUSTER}
    - kubectl -n kube-system get pods
    - "./ci/test_chart.sh $GCP_CLUSTER $CHART_NAME $RELEASE_VERSION"
    - "./ci/deploy_to_repo.sh $S3_BUCKET_NAME $CHART_NAME $RELEASE_VERSION"
env:
  global:
  - HELM_VERSION="v2.16.1"
notifications:
  slack:
    rooms:
      secure: is+EApQDFHhFcWcsNL4qbLeJCmK6RUTPqgiykAAeI56TQgVOCQMLa/hJRHJin9hmIoT2f45hz683hQnAZUlV+Yb6Pn9mSx3B/BD6OcVEPC2cgpkDm80qCYD2FxnfJRKSBeMB0ErhKi+YAtE587nYENOgkZustVLe8TyDouash9bd1OR4Pn5FnfnneCf2GuuCrq+8V0llkbeI11MeNEdTo66uxGHSYxdieMl0qdn07IUxUcj51xYi1C+mh0Q1xNIQZSbs/3GnKBouS7Je5eJLxCQ1mmz5yMU3WrIhYptpUdcIlldpuo+8qL9+mzU+1MJtqcsUqrKUWqQoTYVYk5zw4KmruqIc6pzkO+Uc6OlRf0/4vL7+xGy4h80InlzcCaImqUVaA/wO13zQ6BemAh1DeL+EOyMVP5cgLcle01n88xuk1CZxLk5e7OwZaoM7QBqILNLPcpyukRmCOzVsJEnTJkbe193/+760odcVwH6AEZEFGrLaoBc8RMxkXan3X0X8fz81NtQ8GFefOjtfeJsT9zhC0TaewZRyNzX1LnkUFQwKsfXZ20PMmHs7cUcL1g5XpgwRjWA4Bg1+5ObQFKPTzgwa21661PwaOQnxEbQMRKsbt5rRDZ2cUe7vlPqP6hUULc69B4Fql0YPRq0ttRKtMkf2nktN7+IrbDd+eqbsu6k=
