name: autonity
version: 1.0.10
kubeVersion: ">=1.10.0-0"
description: Deploy production autonity instances
keywords:
- autonity
- blockchain
home: https://www.autonity.io/
sources:
- https://github.com/clearmatics/autonity
maintainers:
- name: eastata
  email: aleksandr.poliakov@clearmatics.com
appVersion: v0.3.0
