name: autonity
version: 1.1.0
kubeVersion: ">=1.12.0-0"
description: Deploy production autonity instances
keywords:
- autonity
- blockchain
home: https://www.autonity.io/
sources:
- https://github.com/clearmatics/autonity
maintainers:
- name: eastata
  email: aleksandr.poliakov@clearmatics.com
appVersion: dev-0.3.0-fix2
