name: autonity-network
version: 0.3.0
kubeVersion: ">=1.10.0-0"
description: Chart for deploy full Autonity network
keywords:
- autonity
- blockchain
home: https://www.autonity.io/
sources:
- https://github.com/clearmatics/autonity
maintainers:
- name: eastata
  email: aleksandr.poliakov@clearmatics.com
appVersion: v0.2.0-alpha
