---

imageAutonity:
  repository: clearmatics/autonity
  tag: v0.1.6

imageAutonity_init:
  repository: clearmatics/autonity-init
  tag: v0.1.1

image_ibft_keys_generator:
  repository: clearmatics/ibft-keys-generator
  tag: v0.0.6

image_ibft_genesis_configurator:
  repository: clearmatics/ibft-genesis-configurator
  tag: v0.0.4

image_nginx:
  repository: nginx
  tag: 1.17-alpine

testFramework:
  image: "dduportal/bats"
  tag: "0.4.0"

# Number of validators and observers
validators:
  num: 4
observers:
  num: 1

chainid: 1488

# Must be: 'istanbul' or 'tendermint'
concensus: tendermint

rpc_http_basic_auth_enabled: false
rpc_https_enabled: false

aws_persistent_storage_enabled: false
gcp_persistent_storage_enabled: false

blockchain_persistent_volume_size: 20G

files_dir: "files"

global:
  ethstats:
    enabled: false
  telepresence:
    enabled: false

