
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ethstats
  namespace: {{ .Release.Namespace }}
  labels:
    app: ethstats
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: ethstats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ethstats
      release: {{ .Release.Name }}
      component: ethstats
  template:
    metadata:
      labels:
        app: ethstats
        release: {{ .Release.Name }}
        component: ethstats
    spec:
      containers:
      - name: ethstats
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: WS_SECRET
          valueFrom:
            secretKeyRef:
              name: ethstats
              key: WS_SECRET
