apiVersion: v1
kind: Secret
metadata:
  name: ethstats
  namespace: {{ .Release.Namespace }}
  labels:
    app: ethstats
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  WS_SECRET: {{ .Values.global.ethstats.webSocketSecret | b64enc | quote }}
