name: autonity-demo
version: 1.1.0
kubeVersion: ">=1.15.11-0"
description: Umbrella chart for Demo deploy autonity-network and supporting tools
keywords:
- autonity
- blockchain
home: https://www.autonity.io/
sources:
- https://github.com/clearmatics/autonity
maintainers:
- name: eastata
  email: aleksandr.poliakov@clearmatics.com
appVersion: v0.4.0
