name: autonity-demo
version: 0.4.5
kubeVersion: ">=1.10.0-0"
description: private Autonity network Helm chart for Kubernetes
keywords:
- autonity
- blockchain
home: https://www.autonity.io/
sources:
- https://github.com/clearmatics/autonity
maintainers:
- name: eastata
  email: aleksandr.poliakov@clearmatics.com
appVersion: 1.8.20
