---
# This settings will install autonity-network with:
#  - persistent storage for autonity validators and observers
#  - persistent storage for prometheus
#  - persistent storage for grafana

global:
  autonity_network:
    enabled: true
  ethstats:
    enabled: false
    webSocketSecret: 3b7Lp5BDdtpNQyFwSjbtMHVU5Xuzo4
  validator_dapp:
    enabled: false
  prometheus:
    enabled: true
  grafana:
    enabled: true
  telepresence:
    enabled: false

autonity-network:
  gcp_persistent_storage_enabled: true
  blockchain_persistent_volume_size: 20G
  chainid: 1489
  networkid: 444888
  validators:
    num: 4
    serviceType: "ClusterIP"
  observers:
    num: 1
    serviceType: "ClusterIP"

prometheus:
  server:
    fullnameOverride: 'autonity-prometheus-server'
    persistentVolume:
      enabled: true
      size: 30Gi
    configMapOverrideName: 'prometheus-server-config'
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  pushgateway:
    enabled: false
  alertmanager:
    enabled: false

grafana:
  persistence:
    enabled: true
    type: pvc
    size: 30Gi
  adminUser: admin
  service:
    port: 80
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://autonity-prometheus-server:80
        access: proxy
        isDefault: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'autonity'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/autonity
  dashboardsConfigMaps:
    autonity: "grafana-dashboard-autonity"
