{{ if .Values.genesis }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: genesis
  namespace: {{ .Release.Namespace }}
data: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: genesis-template
  namespace: {{ .Release.Namespace }}
data:
  genesis:  |-
  {{ toJson .Values.genesis| indent 4 }}
{{end}}
