---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: autonity-node-0
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: autonity-node-0
    spec:
{{ if .Values.aws }}
      nodeSelector:
        ext_ip: "{{ .Values.aws.autonity_node_0.ext_ip }}"
{{ end }}
{{ if .Values.gcp }}
  {{ if .Values.gcp.autonity_node_0.node_selector }}
      nodeSelector:
        {{- range $key, $value := .Values.gcp.autonity_node_0.node_selector }}
        {{ $key }}: {{ $value }}
        {{- end }}
  {{ end }}
{{ end }}
      initContainers:
      - name: init
        image: {{ .Values.imageAutonity_init.repository }}:{{ .Values.imageAutonity_init.tag }}
        volumeMounts:
        - name: blockchain
          mountPath: /autonity/blockchain
        - name: keys
          mountPath: /autonity/keys
        - name: cm-genesis
          mountPath: /autonity/cm-genesis
        - name: sec-account-pwd
          mountPath: /autonity/sec-account-pwd
        - name: sec-peers
          mountPath: /autonity/sec-peers
        args:
          - "--debug"
          - "true"
      containers:
      - name: autonity
        image: {{ .Values.imageAutonity.repository }}:{{ .Values.imageAutonity.tag }}
        ports:
        - containerPort: 30303
          name: p2p
        - containerPort: 6060
          name: metrics
        args:
          - "--datadir"
          - "/autonity/blockchain"
          - "--keystore"
          - "/autonity/keys/keystore"
          - "--nodekey"
          - "/autonity/sec-peers/private_key"
          - "--gcmode"
          - "archive"
          - "--syncmode"
          - "full"
          - "--cache"
          - "1024"
          - "--rpc"
          - "--rpcapi"
          - "eth,web3,net,tendermint,txpool,debug"
          - "--rpcvhosts"
          - "*"
          - "--ws"
          - "--wsapi"
          - "eth,web3,net"
          - "--wsorigins"
          - "*"
          - "--metrics"
          - "--pprof"
          - "--pprofaddr"
          - "0.0.0.0"
          - "--networkid"
          - "{{ .Values.networkid }}"
{{ if eq .Values.mode "validator" }}
          - "--mine"
          - "--minerthreads"
          - "1"
{{ end }}
          - "--debug"
          - "--verbosity"
          - "4"
        volumeMounts:
        - name: blockchain
          mountPath: /autonity/blockchain
        - name: keys
          mountPath: /autonity/keys
        - name: sec-peers
          mountPath: /autonity/sec-peers
      - name: nginx
        image: {{ .Values.image_nginx.repository }}:{{ .Values.image_nginx.tag }}
        ports:
        - containerPort: 8080
          name: https-rpc
        volumeMounts:
        - name: nginx-proxy-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
{{ if .Values.rpc_http_basic_auth_enabled }}
        - name: nginx-proxy-config
          mountPath: /etc/nginx/htpasswd
          subPath: htpasswd
{{ end }}
{{ if .Values.rpc_https_enabled }}
        - name: nginx-proxy-ssl
          mountPath: /etc/nginx/ssl
{{ end }}
{{ if .Values.telegraf }}
      - name: telegraf
        image: {{ .Values.telegraf.repository }}:{{ .Values.telegraf.tag }}
        env:
        - name: NETWORKID
          value: "{{ .Values.networkid }}"
        - name: CLIENT_NAME
          value: "{{ .Values.telegraf.afnc_name }}"
        volumeMounts:
        - name: telegraf-conf
          mountPath: /etc/telegraf/telegraf.conf
          subPath: conf
{{ end }}
      volumes:
        - name: blockchain
{{ if or (eq .Values.aws_persistent_storage_enabled true) (eq .Values.gcp_persistent_storage_enabled true) }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-autonity-node-0-blockchain
{{ else }}
          emptyDir: {}
{{ end}}
        - name: keys
          emptyDir:
            medium: Memory
            sizeLimit: "1M"
        - name: cm-genesis
          configMap:
            name: genesis
            items:
              - key: genesis
                path: genesis.json
        - name: sec-account-pwd
          secret:
            secretName: autonity-node-0
            items:
              - key: password
                path: account.pwd
        - name: sec-peers
          secret:
            secretName: autonity-node-0
            items:
              - key: private_key
                path: private_key
{{ if .Values.telegraf }}
        - name: telegraf-conf
          configMap:
            name: telegraf-conf
{{ end }}
        - name: nginx-proxy-config
          configMap:
            name: nginx-conf

{{ if .Values.rpc_https_enabled }}
        - name: nginx-proxy-ssl
          secret:
            secretName: autonity-https
{{ end }}
