---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-job01-ibft-keys-generator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: autonity-initiator
      containers:
      - name: init-job01-ibft-keys-generator
        image: {{ .Values.image_ibft_keys_generator.repository }}:{{ .Values.image_ibft_keys_generator.tag }}
        args:
          - "--validators"
          - "{{ .Values.validators }}"
          - "--observers"
          - "{{ .Values.observers }}"
      restartPolicy: Never
  backoffLimit: 0
