---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-job02-ibft-genesis-configurator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: autonity-initiator
      restartPolicy: Never
      containers:
      - name: init-job02-ibft-genesis-configurator
        image: {{ .Values.image_ibft_genesis_configurator.repository }}:{{ .Values.image_ibft_genesis_configurator.tag }}
        volumeMounts:
          - name: validators
            mountPath: /autonity/validators
          - name: observers
            mountPath: /autonity/observers
          - name: genesis-template
            mountPath: /autonity
      volumes:
        - name: validators
          configMap:
            name: validators
        - name: observers
          configMap:
            name: observers
        - name: genesis-template
          configMap:
            name: genesis-template
            items:
              - key: genesis.json
                path: genesis-template.json

  backoffLimit: 0
