---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autonity-keys-generator
  namespace: {{ .Release.Namespace }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secrets-write
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["validator-0"]
  verbs: ["patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["validator-0"]
  verbs: ["patch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secrets-write
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: secrets-write
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: autonity-keys-generator
  namespace: {{ .Release.Namespace }}



---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autonity-genesis-configurator
  namespace: {{ .Release.Namespace }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: genesis-write
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["genesis"]
  verbs: ["patch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: genesis-write
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: genesis-write
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: autonity-genesis-configurator
  namespace: {{ .Release.Namespace }}