---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autonity-initiator
  namespace: {{ .Release.Namespace }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secrets-write
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["account-pwd", "validators", "observers"]
  verbs: ["patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["validators", "observers", "genesis"]
  verbs: ["patch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secrets-write
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: secrets-write
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: autonity-initiator
  namespace: {{ .Release.Namespace }}
