{{- if .Values.rpc_https_enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: autonity-https
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.rpc.tls_crt }}
  tls.key: {{ .Values.rpc.tls_key }}
  dhparam.pem: {{ .Values.rpc.dhparam_pem }}
---
{{- end }}
