---
apiVersion: v1
kind: Service
metadata:
  name: validator-0
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/port: "6060"
    prometheus.io/path: "/debug/metrics/prometheus"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: https-rpc
      port: 8545
      targetPort: 8080
    - protocol: TCP
      name: wss
      port: 8546
      targetPort: 8081
    - protocol: TCP
      name: metrics
      port: 9200
      targetPort: 9200
  selector:
    app: validator-0

---
apiVersion: v1
kind: Service
metadata:
  name: p2p-validator-0
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      name: p2p
      port: 30303
{{ if .Values.aws }}
      nodePort: {{ .Values.aws.validator_0.port }}
  type: NodePort
{{ else }}
      targetPort:  30303
  type: LoadBalancer
{{ end }}
  selector:
    app: validator-0
