---
apiVersion: v1
kind: Service
metadata:
  name: autonity-node-0
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/port: "6060"
    prometheus.io/path: "/debug/metrics/prometheus"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: https-rpc
      port: 8545
      targetPort: 8080
    - protocol: TCP
      name: wss
      port: 8546
      targetPort: 8081
    - protocol: TCP
      name: metrics
      port: 6060
      targetPort: 6060
  selector:
    app: autonity-node-0

---
apiVersion: v1
kind: Service
metadata:
  name: p2p-autonity-node-0
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      name: p2p
      targetPort:  30303
{{ if .Values.aws }}
      port: {{ .Values.aws.autonity_node_0.port }}
      nodePort: {{ .Values.aws.autonity_node_0.port }}
  type: NodePort
{{ else if .Values.gcp }}
      port: 30303
  type: LoadBalancer
  loadBalancerIP: {{ .Values.gcp.autonity_node_0.ext_ip }}
{{ else }}
      port: 30303
  type: LoadBalancer
{{ end }}
  selector:
    app: autonity-node-0

---
{{ if .Values.rpc_public }}
apiVersion: v1
kind: Service
metadata:
  name: public-rpc-autonity-node-0
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      name: https-rpc
      port: 8545
      targetPort: 8080
    - protocol: TCP
      name: wss
      port: 8546
      targetPort: 8081
  type: LoadBalancer
{{ if .Values.rpc_public.src_ip_whitelist }}
  loadBalancerSourceRanges:
  {{- range .Values.rpc_public.src_ip_whitelist }}
    - {{ . }}
  {{- end }}
{{ end }}
  selector:
    app: autonity-node-0
{{ end }}
