name: "Integration Tests"

on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  integration_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      name: git checkout

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo $GITHUB_HEAD_REF $GITHUB_RUN_NUMBER > /tmp/test

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        cat /tmp/test
        echo One job
